from ontology import ContentItem, ContentType

CONTENT_LIBRARY: list[ContentItem] = [
    # --- セミナー (5件) ---
    ContentItem(
        id="seminar_01",
        content_type=ContentType.SEMINAR_UPCOMING,
        name="【2026年最新】ベテラン退職に備える「技能伝承」デジタル化の具体策",
        description="熟練工の勘やコツが若手に伝わらず、暗黙知のまま失われていく課題を解決するためのウェビナーです。スマホやタブレットを活用し、現場の負担を最小限に抑えながら動画マニュアルや技能アーカイブを構築するステップを解説します。対象：工場長、生産技術部責任者、人事開発担当者",
        url="https://example.com/seminar-skill-transfer",
    ),
    ContentItem(
        id="seminar_02",
        content_type=ContentType.SEMINAR_UPCOMING,
        name="脱・Excelマクロ！壊れかけのスキルマップから脱却する現場主導のDX",
        description="「拠点ごとに評価基準がバラバラ」「マクロが重くて更新が形骸化している」といった、製造現場のスキル管理あるあるを解消するセミナーです。現場の職長や班長が迷わずリアルタイムに入力でき、多能工化の進捗を正しく可視化するシステム運用のコツを紹介します。対象：製造部責任者、DX推進室、工場管理室",
        url="https://example.com/seminar-excel-out",
    ),
    ContentItem(
        id="seminar_03",
        content_type=ContentType.SEMINAR_UPCOMING,
        name="化学・金属プラント必見：法定資格の期限切れリスクを防ぐコンプライアンス講座",
        description="ボイラー、危険物、クレーンなど、製造現場に不可欠な各種国家資格や安全講習の有効期限。Excel管理の限界による失効リスクに怯える総務・安全管理部門向けの危機管理セミナーです。アラート機能を活用した自動化と受講履歴の一元管理手法を学びます。対象：安全環境管理室、総務部長、コンプライアンス担当",
        url="https://example.com/seminar-safety-compliance",
    ),
    ContentItem(
        id="seminar_04",
        content_type=ContentType.SEMINAR_UPCOMING,
        name="突発的な欠勤・応援に対応する「要員配置自動シミュレーション」の仕組み",
        description="「誰がどのラインに入れるか」の判断が特定のベテランに属人化していませんか？派遣・契約社員を含むスタッフのリアルタイムなスキルデータを基に、急な配置転換やラインごとの適正シフトを自動でパズルのように最適化する手法をデモを交えて解説します。対象：生産管理課、工場長、組立ラインリーダー",
        url="https://example.com/seminar-allocation-sim",
    ),
    ContentItem(
        id="seminar_05",
        content_type=ContentType.SEMINAR_UPCOMING,
        name="製造業の早期離職を防ぐ！未経験者を3ヶ月で一本立ちさせる育成カリキュラム設計",
        description="「せっかく採用した若手がすぐに辞めてしまう」「現場の教え方にバラつきがある」という課題を解決します。スキルマップと育成テンプレートを連動させ、成長を本人と管理者がステップバイステップで確認できる環境づくりの成功パターンを公開。対象：人事部、採用主任、製造現場の教育担当",
        url="https://example.com/seminar-retention-hr",
    ),
    # --- イベント (5件) ---
    ContentItem(
        id="event_01",
        content_type=ContentType.EVENT_UPCOMING,
        name="【実機体験】現場が「これなら使える」と太鼓判を押すタブレット端末体験会",
        description="PCやITツールに苦手意識のある現場の職長・作業員の方を対象とした、ハンズオン型の操作体験会です。クリーンルーム内や騒音のある工場内を想定し、手袋をはめたままでも迷わず操作できるUI/UXを、実際のデモ機を触りながら実感いただけます。対象：現場の職長、班長、メンテナンス課責任者",
        url="https://example.com/event-hands-on",
    ),
    ContentItem(
        id="event_02",
        content_type=ContentType.EVENT_UPCOMING,
        name="他社の失敗・成功を本音で語る「製造業人材DX推進者」限定ラウンドテーブル",
        description="同業他社のDX推進者や工場長が集まり、現場へのツール定着の壁や、総務・経営層との予算交渉の裏側など、セミナーでは話せない「生々しい悩み」を少人数でディスカッションする情報交換会です。他社の取り組みを自社のブレイクスルーに。対象：製造業のDX推進室マネージャー、工場長（事前審査制）",
        url="https://example.com/event-round-table",
    ),
    ContentItem(
        id="event_03",
        content_type=ContentType.EVENT_UPCOMING,
        name="自社の課題を持ち寄り！その場で作る「スキルマップ基準策定」ワークショップ",
        description="自社で現在使っているExcelシートや紙のチェックリストをお持ち込みいただき、プロのコンサルタントと一緒に「拠点間で標準化できる共通スキル基準」の骨子をその場で設計する実践型ワークショップです。持ち帰ってすぐに使える設計書を作成します。対象：人事部人材開発グループ、品質保証部責任者",
        url="https://example.com/event-workshop-map",
    ),
    ContentItem(
        id="event_04",
        content_type=ContentType.EVENT_UPCOMING,
        name="第5回 スマート工場EXPO [秋] 出展・個別デモブース案内",
        description="アジア最大級のスマート工場展示会に出展します。ブース内では「技能伝承アーカイブ」「要員配置シミュレーター」の最新機能のデモを常時実施。事前にご予約いただいた方には、現場の生産データと人のスキルデータをAPI連携させるための技術仕様相談も承ります。対象：スマートファクトリー化を検討中の経営層、情報システム部門",
        url="https://example.com/event-expo-autumn",
    ),
    ContentItem(
        id="event_05",
        content_type=ContentType.EVENT_UPCOMING,
        name="【今期予算活用】15分でスピード診断！「現場の人材課題」個別オンライン相談会",
        description="「何から始めればいいかわからない」「今秋の選定に向けて概算の見積もりや他社比較表が急ぎで欲しい」といったご要望に、専任スタッフがマンツーマンでお答えする短時間のオンライン相談会です。貴社の工場規模や現在の利用ツールに合わせたPoC（検証）プランをご提示します。対象：決裁権を持つ工場長、総務・人事責任者",
        url="https://example.com/event-quick-consulting",
    ),
    # --- 資料 (5件) ---
    ContentItem(
        id="doc_01",
        content_type=ContentType.WHITE_PAPER,
        name="製造現場のための「形骸化しないスキルマップ」作成・導入完全ガイド",
        description="現場に嫌われないスキルマップの作り方をステップ形式で解説したホワイトペーパーです。検査員のスキル認定基準の標準化や、多能工化のレーダーチャートの作り方を網羅。そのまま加工して使える「製造業特有のスキル項目サンプル集（Excel形式）」が特典として付属します。対象課題：評価の不公平感、スキル管理の属人化",
        url="https://example.com/doc-skillmap-guide",
    ),
    ContentItem(
        id="doc_02",
        content_type=ContentType.WHITE_PAPER,
        name="職人の「頑固さ」を乗り越える！熟練ノウハウを動画で残す技能伝承マニュアル",
        description="「技術は見て覚えろ」というベテラン職人に協力してもらい、感覚的な金型設計や鋳造の配合ノウハウをデジタル動画化するためのアプローチ術をまとめた一冊です。スマートフォンの撮影アングルや、暗黙知を言語化するための質問リストを掲載。対象課題：教える時間が取れない、特定のベテランへの業務集中",
        url="https://example.com/doc-video-transfer",
    ),
    ContentItem(
        id="doc_03",
        content_type=ContentType.CASE_STUDY,
        name="【2026年最新版】町工場から大手プラントまで：製造業の人材DX成功事例集",
        description="15名の町工場での動画マニュアル活用から、1,000名規模のグループ企業におけるスキル共通化プロジェクトまで、日本の製造現場における最新の人材DX成功事例を10社厳選して収録。導入前後の投資対効果（ROI）や、現場の生の声を掲載しています。対象課題：全社的なDX推進、費用対効果の社内説明",
        url="https://example.com/doc-case-studies",
    ),
    ContentItem(
        id="doc_04",
        content_type=ContentType.WHITE_PAPER,
        name="工場長・総務必見！法定資格・安全衛生講習「管理体制チェックシート」",
        description="自社の資格管理体制がコンプライアンスを満たしているかをセルフチェックできるシートです。クレーン・フォークリフト・危険物等の期限管理漏れを防ぐための運用フローの見直しや、派遣・契約社員のスキルシート一元化のポイントをまとめています。対象課題：資格失効リスク、コンプライアンス遵守、総務の手間削減",
        url="https://example.com/doc-safety-checklist",
    ),
    ContentItem(
        id="doc_05",
        content_type=ContentType.WHITE_PAPER,
        name="【主要3社を徹底比較】失敗しない「製造現場向け人材管理ツール」選定ポイント",
        description="一般的な人事評価用SaaSと、製造現場に特化したツールの違いを明確にした比較表です。「現場用のタブレット対応か」「API連携機能はあるか」「セキュリティチェックシートのひな形は揃っているか」など、システム選定時に稟議書へ書くべき重要な評価軸を網羅。対象課題：ツール選定の迷い、自社システムとの連携可否",
        url="https://example.com/doc-vendor-comparison",
    ),
]

CONTENT_LIBRARY_BY_ID: dict[str, ContentItem] = {item.id: item for item in CONTENT_LIBRARY}
